apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    {{- with .Values.redis.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-redis-config
        resources:
          requests:
            memory: "{{ .Values.redis.resources.requests.memory }}"
            cpu: "{{ .Values.redis.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.redis.resources.limits.memory }}"
            cpu: "{{ .Values.redis.resources.limits.cpu }}"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10