redis:
  replicaCount: 1
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  additionalLabels:
    environment: dev
    team: backend
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    logFormat: "json"
    logLevel: "info"
    loki.io/logs: "true"
    loki.io/format: "json"
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"

inventory:
  replicaCount: 1
  image:
    repository: touqeerjadoon55/shipr-inventory
    tag: 1.0.1
    pullPolicy: IfNotPresent
  service:
    port: 8000
    nodePort: 30002
    type: NodePort
  additionalLabels:
    environment: dev
    team: backend
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    logFormat: "json"
    logLevel: "info"
    loki.io/logs: "true"
    loki.io/format: "json"
  env:
    REDIS_HOST: shipr-redis
    REDIS_PORT: "6379"
    REDIS_DB: "0"
    ALLOW_ORIGINS: "http://192.168.49.2:30001"
    ALLOW_METHODS: "*"
    ALLOW_HEADERS: "*"
    PRODUCT_SERVICE_URL: http://192.168.49.2:30002
    FEE_PERCENTAGE: "5"
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"

payment:
  replicaCount: 1
  image:
    repository: touqeerjadoon55/shipr-payment
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    port: 8001
    nodePort: 30003
    type: NodePort
  additionalLabels:
    environment: dev
    team: backend
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    logFormat: "json"
    logLevel: "info"
    loki.io/logs: "true"
    loki.io/format: "json"
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"

frontend:
  replicaCount: 1
  image:
    repository: touqeerjadoon55/frontend-shiprapp
    tag: 1.0.4
    pullPolicy: IfNotPresent
  inventory:
    url: http://192.168.49.2:30002
  payment:
    url: http://192.168.49.2:30003
  service:
    port: 80
    nodePort: 30001
    type: NodePort
  additionalLabels:
    environment: dev
    team: frontend
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
    logFormat: "json"
    logLevel: "info"
    loki.io/logs: "true"
    loki.io/format: "json"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

consumer:
  inventory:
    replicaCount: 1
    image:
      repository: touqeerjadoon55/shipr-inventory-consumer
      tag: 1.0.1
      pullPolicy: IfNotPresent
    redis:
      configMap: shipr-redis-config
    command:
    - python
    - consumer.py
    additionalLabels:
      environment: dev
      team: backend
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
      logFormat: "json"
      logLevel: "info"
      loki.io/logs: "true"
      loki.io/format: "json"
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"

  payment:
    replicaCount: 1
    image:
      repository: touqeerjadoon55/shipr-payment-consumer
      tag: 1.0.0
      pullPolicy: IfNotPresent
    redis:
      configMap: shipr-redis-config
    command:
    - python
    - consumer.py
    additionalLabels:
      environment: dev
      team: backend
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
      logFormat: "json"
      logLevel: "info"
      loki.io/logs: "true"
      loki.io/format: "json"
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
