apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-payment-consumer
spec:
  replicas: {{ .Values.consumer.payment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-payment-consumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-payment-consumer
    spec:
      containers:
      - name: payment-consumer
        image: "{{ .Values.consumer.payment.image.repository }}:{{ .Values.consumer.payment.image.tag }}"
        command: [ "python", "consumer.py" ]
        envFrom:
        - configMapRef:
            name: {{ .Values.consumer.payment.redis.configMap }}
        resources:
          requests:
            memory: "{{ .Values.consumer.payment.resources.requests.memory }}"
            cpu: "{{ .Values.consumer.payment.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.consumer.payment.resources.limits.memory }}"
            cpu: "{{ .Values.consumer.payment.resources.limits.cpu }}"