apiVersion: v1
kind: ConfigMap
metadata:
  name: shipr-inventory-config
data:
  REDIS_HOST: {{ .Values.inventory.redis.host }}
  REDIS_PORT: "{{ .Values.inventory.redis.port }}"
  REDIS_DB: "{{ .Values.inventory.redis.db }}"
  ALLOW_ORIGINS: "{{ .Values.inventory.allowOrigins }}"
  ALLOW_METHODS: "{{ .Values.inventory.allowMethods }}"
  ALLOW_HEADERS: "{{ .Values.inventory.allowHeaders }}"
